[package]
name = "rose-offline-client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.4"
arrayvec = "0.7"
bevy = { version = "0.8.0-dev", features = ["dds", "tga"] }
bevy_egui = "0.14.0"
bevy-inspector-egui = "0.10.0"
bevy_polyline = "0.1"
bevy_rapier3d = "0.13.1"
bitflags = "1.2"
bytemuck = { version = "1.7.0", features = ["derive"] }
clap = "3.1"
crossbeam-channel = "0.5"
egui_extras = "0.18"
enum-map = { version = "2.0", features = ["serde"] }
image = { version = "0.23", default-features = false, features = ["dds"] }
lazy_static = "1.4.0"
log = "0.4.14"
md5 = "0.7.0"
num-derive = "0.3"
num-traits = "0.2"
rand = "0.8"
smooth-bevy-cameras = "0.2.0"
thiserror = "1.0"
tokio = { version = "1.17", features = ["rt", "net", "sync", "macros", "io-util"] }
rose-data = { git = "https://github.com/exjam/rose-offline", rev = "02e7741c99e9898a900b187a1c93d0c299432d3d" }
rose-data-irose = { git = "https://github.com/exjam/rose-offline", rev = "02e7741c99e9898a900b187a1c93d0c299432d3d" }
rose-file-readers = { git = "https://github.com/exjam/rose-offline", rev = "02e7741c99e9898a900b187a1c93d0c299432d3d" }
rose-game-common = { git = "https://github.com/exjam/rose-offline", rev = "02e7741c99e9898a900b187a1c93d0c299432d3d" }
rose-game-irose = { git = "https://github.com/exjam/rose-offline", rev = "02e7741c99e9898a900b187a1c93d0c299432d3d" }
rose-network-common = { git = "https://github.com/exjam/rose-offline", rev = "02e7741c99e9898a900b187a1c93d0c299432d3d" }
rose-network-irose = { git = "https://github.com/exjam/rose-offline", rev = "02e7741c99e9898a900b187a1c93d0c299432d3d" }

[patch.crates-io]
bevy = { git = "https://github.com/exjam/bevy", rev = "bb8ca7f0cfb3f678a17f84cd25885f8e1eafb2ca" }
bevy_polyline = { git = "https://github.com/exjam/bevy_polyline", rev = "3dd7821086b21e6d719184b2d1553514c135c193" }
bevy_egui = { git = "https://github.com/exjam/bevy_egui", rev = "143bb5e864fd7fa26b189c3b9904bfbb131c41b0" }
bevy-inspector-egui = { git = "https://github.com/exjam/bevy-inspector-egui", rev = "5ab02c77dc41f57004f541fd679b06f4ce1eb4c5" }
bevy_rapier3d = { git = "https://github.com/exjam/bevy_rapier", rev = "27bbad14175370615a01ee1701cb8ebae92faaa5" }
smooth-bevy-cameras = { git = "https://github.com/exjam/smooth-bevy-cameras", rev = "9361f1181b8dda71219dfab0c299624fb7e5d19a" }
image = { git = "https://github.com/image-rs/image", branch = "version-0.23" }

[profile.dev.package."*"]
opt-level = 3
